apiVersion: v1
kind: ServiceAccount
metadata:
  name: valheim-password-rotator
  namespace: valheim
imagePullSecrets:
- name: registry-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: valheim-secret-editor
  namespace: valheim
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["valheim-pass"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["valheim-server"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-valheim-secret-editor
  namespace: valheim
subjects:
- kind: ServiceAccount
  name: valheim-password-rotator
roleRef:
  kind: Role
  name: valheim-secret-editor
  apiGroup: rbac.authorization.k8s.io
