apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-world-data
  namespace: valheim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-base-data
  namespace: valheim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path