apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
  namespace: valheim
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: valheim-server
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: valheim-server
    spec:
      imagePullSecrets:
      - name: registry-secret
      tolerations:
        - key: "arch"
          operator: "Equal"
          value: "amd64"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - env:
        - name: BACKUPS_CRON
          value: "0 0 * * *"
        - name: BACKUP_MAX_AGE
          value: "10"
        - name: SERVER_NAME
          value: crowheim2-electric-boogaloo
        - name: WORLD_NAME
          value: crowheim2-electric-boogaloo
        - name: SERVER_PASS
          valueFrom:
            secretKeyRef:
              name: valheim-pass
              key: SERVER_PASS
        - name: SERVER_PORT
          value: "2456"
        #image: lloesche/valheim-server:latest
        image: registry.lan.ccrow.org/lloesche/valheim-server:latest
        imagePullPolicy: Always
        name: valheim-server
        ports:
        - containerPort: 2456
          name: gameport
          protocol: TCP
        - containerPort: 2457
          name: queryport
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: gamefiles
        - mountPath: /opt/valheim
          name: serverfiles
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gamefiles
        persistentVolumeClaim:
          claimName: valheim-server-world-data
      - name: serverfiles
        persistentVolumeClaim:
          claimName: valheim-server-base-data
