apiVersion: batch/v1
kind: CronJob
metadata:
  name: valheim-password-rotate
  namespace: valheim
spec:
  schedule: "0 4 * * *"
  timeZone: "US/Pacific"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: valheim-password-rotator
          restartPolicy: OnFailure
          containers:
          - name: rotate-password
            image: registry.lan.ccrow.org/debian-custom:latest
            imagePullPolicy: Always
            env:
            - name: SECRET_NAME
              value: valheim-pass
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: discord-password-url
                  key: DISCORD_WEBHOOK
            - name: SECRET_KEY
              value: SERVER_PASS
            - name: DEPLOYMENT_NAME
              value: valheim-server
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            command:
            - /bin/bash
            - -c
            - |
              set -ex
              PASSWORD=$(shuf -n 1 words.txt | tr -d '\r\n')

              echo "New password: $PASSWORD"

              kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o json | \
                jq --arg pw "$(echo -n "$PASSWORD" | base64)" \
                   '.data[$ENV.SECRET_KEY] = $pw' | \
                kubectl apply -f -

              notify_discord.sh "new valheim server password is $PASSWORD"

              kubectl rollout restart deployment/"$DEPLOYMENT_NAME" -n "$NAMESPACE"
